#!/usr/bin/bash
# Maintainer  : Vilmar Catafesta <vcatafesta@gmail.com>

pkgname=voidbr-utils
pkgdesc="Utilitários do sistema essencias para uso diário no Void Linux"
pkgver=$(date +%Y%m%d)
pkgrel=$(date +%H%M)
arch=('any')
license=('GPL3')
url="https://github.com/voidlinuxbr/$pkgname"
provides=("$pkgname")
source=("git+${url}.git")
md5sums=('SKIP')
depends=("bash>=0")

package() {
	local dirs=("usr" "etc" "opt")
	#   echo "DESTDIR=$DESTDIR"
	#   echo "pkgdir=$pkgdir"
	#   echo "srcdir=$srcdir"
	#   echo "_pkgsrc=$_pkgsrc"

	cd ${srcdir}/${pkgname}
	for dir in "${dirs[@]}"; do
		if [ -d "${_pkgsrc}/${dir}" ]; then
			cp -a "${_pkgsrc}/${dir}" "$DESTDIR/"
		fi
	done
}
