#!/usr/bin/env bash
# NOTE: Imported from Arch Linux/AUR
# Maintainer: Vilmar Catafesta <vcatafesta@gmail.com>
# Maintainer: Carl Smedstad <carsme@archlinux.org>
# Maintainer: Sven-Hendrik Haase <svenstaro@archlinux.org>

pkgname=opencode
pkgver=2.0.8
pkgrel=1
pkgdesc='The open source coding agent'
arch=('x86_64')
url='https://github.com/anomalyco/opencode'
license=('MIT')
depends=(
	'curl'
	'glibc'
	'icu'
	'ripgrep'
	'tar'
)
#checkdepends=(
#  'nodejs-lts-jod'
#)
makedepends=(
	'bun'
	'git'
)
optdepends=(
	'wl-clipboard: clipboard support on Wayland'
	'xclip: clipboard support on X11'
)
options=(
	'!debug'
	'!strip'
)
source=("git+$url.git#tag=v$pkgver")
b2sums=('1288de1314f02a21c06406bf2f4530b849acc056431c6d73c7ce092d456be4f25ff762b376552fb2ef03c83cc637c41838116bef4f8fcf2b6b1d6e9b456ac7c9')

prepare() {
	cd $pkgname
	sed -i 's|"packageManager": "bun@1.4.2"|"packageManager": "bun@1.4.0"|' package.json
	bun install --frozen-lockfile --ignore-scripts
}

build() {
	cd $pkgname/packages/cli
	OPENCODE_VERSION=$pkgver bun run ./script/build.ts --single --baseline --skip-install
}

#check() {
#  cd $pkgname/packages/opencode

# I _really_ tried to make the tests work but I'm getting 100s of failures, mostly due to this I think:
# https://github.com/oven-sh/bun/issues/30014
# Let's revisit this once the bug is fixed.
#
# export GIT_CONFIG_GLOBAL=$PWD/gitconfig
# git config --global user.email "builduser@archlinux.org"
# git config --global user.name "Build User"
# bun test --timeout=20000 --parallel
#}

package() {
	cd $pkgname
	case $CARCH in
	aarch64) dir=cli-linux-arm64 ;;
	x86_64) dir=cli-linux-x64-baseline ;;
	esac
	install -vDm755 -t "$pkgdir/usr/bin" "packages/cli/dist/$dir/bin/opencode"

	install -vDm644 -t "$pkgdir/usr/share/licenses/$pkgname" LICENSE

	"$pkgdir/usr/bin/opencode" --completions bash |
		install -vDm644 /dev/stdin "$pkgdir/usr/share/bash-completion/completions/opencode"
	"$pkgdir/usr/bin/opencode" --completions zsh |
		install -vDm644 /dev/stdin "$pkgdir/usr/share/zsh/site-functions/_opencode"
}

pre_install() {
	log "Iniciando instalação"
}

post_install() {
	log "Finalizando instalação"
}

pre_upgrade() {
	log "Iniciando upgrade"
}

post_upgrade() {
	log "Finalizando upgrade"
}
