#!/usr/bin/env bash
# Maintainer: Catafesta <vcatafesta@chililinux.com>

pkgname=nano
pkgver=9.1
pkgrel=1
pkgdesc="Pico editor clone with enhancements"
license="GPL-3.0-or-later"
url="https://www.nano-editor.org"
depends=('ncurses' 'file' 'glibc')
makedepends="autoconf automake libtool pkg-config make gcc ncurses-devel"
source=(https://www.nano-editor.org/dist/v8/${pkgname}-${pkgver}.tar.xz{,.asc})

build() {
	cd "${srcdir}/${pkgname}-${pkgver}"
	./configure \
		--prefix=/usr \
		--sysconfdir=/etc \
		--enable-utf8 \
		--enable-color \
		--enable-multibuffer \
		--enable-nanorc
	make
}

package() {
	cd "${srcdir}/${pkgname}-${pkgver}"
   make DESTDIR="$pkgdir" install
}

pre_install() {
  log "Iniciando instalação"
}

post_install() {
  log "Finalizando instalação"
}

pre_upgrade() {
  log "Iniciando upgrade"
}

post_upgrade() {
  log "Finalizando upgrade"
}


